-- KUBATA KIÉ — final security checks (run with separate test accounts)
-- 1) Anonymous SELECT from profiles must return no rows/permission denied.
-- 2) Authenticated user can SELECT only own profile.
-- 3) Admin can SELECT profiles.
-- 4) Authenticated inquiry with another user's user_id must be rejected.
-- 5) Anonymous inquiry must use user_id NULL.
-- 6) Direct INSERT into notifications must be rejected.
-- 7) Direct UPDATE of messages must be rejected.
-- 8) mark_messages_read() works only for conversation participants.
-- 9) Direct payment status/amount update must be rejected for normal users.
-- 10) cancel_payment() only cancels the caller's pending payment.
-- 11) Direct viewing status manipulation by a client must be rejected.
-- 12) Direct service request updates are restricted to agent/admin.
-- 13) Admin-only RPCs must reject non-admin callers.
-- 14) Storage policies allow only owner/admin upload/delete paths.
