import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Search, MapPin, Hop as Home, Building, TreePine, Store, Warehouse, ArrowRight, TrendingUp, Shield, Users, Camera } from 'lucide-react';
import { getFeaturedProperties, getPropertyImages } from '@/services/propertyService';
import { trackEvent, AnalyticsEvents } from '@/services/analyticsService';
import PropertyCard from '@/components/PropertyCard';
import type { Property } from '@/types';

const HERO_IMAGE='https://images.pexels.com/photos/7909269/pexels-photo-7909269.jpeg?auto=compress&cs=tinysrgb&w=1920';
const AREA_IMAGES=[
  ['Talatona','Luanda','https://images.pexels.com/photos/2767923/pexels-photo-2767923.jpeg?auto=compress&cs=tinysrgb&w=940'],
  ['Miramar','Luanda','https://images.pexels.com/photos/16094813/pexels-photo-16094813.jpeg?auto=compress&cs=tinysrgb&w=940'],
  ['Belas','Luanda','https://images.pexels.com/photos/36834747/pexels-photo-36834747.jpeg?auto=compress&cs=tinysrgb&w=940'],
  ['Ilha de Luanda','Luanda','https://images.pexels.com/photos/37211263/pexels-photo-37211263.jpeg?auto=compress&cs=tinysrgb&w=940'],
];
const DEMO_IMAGES=[
'https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=1200',
'https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=1200',
'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=1200',
'https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=1200',
'https://images.pexels.com/photos/7031604/pexels-photo-7031604.jpeg?auto=compress&cs=tinysrgb&w=1200',
'https://images.pexels.com/photos/534151/pexels-photo-534151.jpeg?auto=compress&cs=tinysrgb&w=1200'];
const DEMO: Property[] = [
  {id:'demo-1',owner_id:'demo',title:'Vivenda contemporânea com piscina em Talatona',description:'Exemplo de apresentação Kubata Kié.',price:125000000,currency:'AOA',property_type:'house',transaction_type:'sale',status:'published',bedrooms:4,bathrooms:4,area:360,land_area:600,address:'Talatona',city:'Luanda',region:'Luanda',country:'Angola',latitude:null,longitude:null,features:{pool:true,security:true},is_featured:true,views_count:428,created_at:new Date().toISOString(),updated_at:new Date().toISOString()},
  {id:'demo-2',owner_id:'demo',title:'Apartamento T3 premium com vista em Miramar',description:'Exemplo de apresentação Kubata Kié.',price:85000000,currency:'AOA',property_type:'apartment',transaction_type:'sale',status:'published',bedrooms:3,bathrooms:3,area:190,land_area:null,address:'Miramar',city:'Luanda',region:'Luanda',country:'Angola',latitude:null,longitude:null,features:{balcony:true,parking:true},is_featured:true,views_count:315,created_at:new Date().toISOString(),updated_at:new Date().toISOString()},
  {id:'demo-3',owner_id:'demo',title:'Moradia T4 mobilada para arrendamento',description:'Exemplo de apresentação Kubata Kié.',price:2200000,currency:'AOA',property_type:'house',transaction_type:'rent',status:'published',bedrooms:4,bathrooms:4,area:280,land_area:500,address:'Benfica',city:'Luanda',region:'Luanda',country:'Angola',latitude:null,longitude:null,features:{furnished:true,generator:true},is_featured:true,views_count:289,created_at:new Date().toISOString(),updated_at:new Date().toISOString()},
  {id:'demo-4',owner_id:'demo',title:'Terreno residencial para investimento',description:'Exemplo de apresentação Kubata Kié.',price:32000000,currency:'AOA',property_type:'land',transaction_type:'sale',status:'published',bedrooms:null,bathrooms:null,area:1000,land_area:1000,address:'Belas',city:'Luanda',region:'Luanda',country:'Angola',latitude:null,longitude:null,features:{water:true,electricity:true},is_featured:false,views_count:201,created_at:new Date().toISOString(),updated_at:new Date().toISOString()},
  {id:'demo-5',owner_id:'demo',title:'Espaço comercial na avenida principal',description:'Exemplo de apresentação Kubata Kié.',price:65000000,currency:'AOA',property_type:'commercial',transaction_type:'sale',status:'published',bedrooms:null,bathrooms:2,area:240,land_area:null,address:'Maianga',city:'Luanda',region:'Luanda',country:'Angola',latitude:null,longitude:null,features:{parking:true,security:true},is_featured:false,views_count:176,created_at:new Date().toISOString(),updated_at:new Date().toISOString()},
  {id:'demo-6',owner_id:'demo',title:'Escritório moderno para arrendamento',description:'Exemplo de apresentação Kubata Kié.',price:1200000,currency:'AOA',property_type:'office',transaction_type:'rent',status:'published',bedrooms:null,bathrooms:2,area:150,land_area:null,address:'Ingombota',city:'Luanda',region:'Luanda',country:'Angola',latitude:null,longitude:null,features:{internet:true,security:true},is_featured:false,views_count:143,created_at:new Date().toISOString(),updated_at:new Date().toISOString()}
];

export default function HomePage(){
 const navigate=useNavigate(); const [featured,setFeatured]=useState<Property[]>([]); const [images,setImages]=useState<Record<string,string>>({}); const [query,setQuery]=useState(''); const [loading,setLoading]=useState(true);
 useEffect(()=>{ let alive=true; getFeaturedProperties(6).then(async p=>{ if(!alive)return; const list=p.length?p:DEMO; setFeatured(list); const map:Record<string,string>={}; await Promise.all(list.map(async (x,i)=>{ if(x.id.startsWith('demo-')) map[x.id]=DEMO_IMAGES[i%DEMO_IMAGES.length]; else { const imgs=await getPropertyImages(x.id).catch(()=>[]); if(imgs[0]) map[x.id]=imgs[0].url; }})); if(alive)setImages(map); }).catch(()=>{if(alive){setFeatured(DEMO); const m:Record<string,string>={}; DEMO.forEach((x,i)=>m[x.id]=DEMO_IMAGES[i]); setImages(m);}}).finally(()=>alive&&setLoading(false)); return()=>{alive=false}; },[]);
 const search=(e:React.FormEvent)=>{e.preventDefault(); trackEvent(AnalyticsEvents.SEARCH,{search_query:query}); navigate(`/properties?search=${encodeURIComponent(query)}`)};
 const cats=[[Home,'Vivendas','house'],[Building,'Apartamentos','apartment'],[TreePine,'Terrenos','land'],[Store,'Escritórios','office'],[Warehouse,'Armazéns','warehouse'],[Store,'Comercial','commercial']] as const;
 return <div>
  <section className="relative min-h-[82vh] flex items-center overflow-hidden"><div className="absolute inset-0"><img src={HERO_IMAGE} alt="Luanda" className="h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-b from-ink-900/75 via-ink-900/55 to-ink-900/85"/></div>
   <div className="relative z-10 container-mw container-px w-full pt-28 pb-28"><div className="max-w-3xl"><div className="mb-6 flex items-center gap-3 animate-fade-in-down"><div className="gold-line"/><span className="text-xs font-medium uppercase tracking-[.2em] text-gold">Plataforma PropTech de Angola</span></div><h1 className="font-serif text-4xl font-bold leading-[1.1] text-white sm:text-5xl lg:text-7xl text-balance animate-fade-in-up">Encontre onde a sua <span className="text-gold">próxima história</span> começa.</h1><p className="mt-6 max-w-xl text-base leading-relaxed text-white/80 sm:text-lg">Pesquise, visite, negoceie e conclua — com a confiança de uma plataforma construída para Angola.</p></div>
   <form onSubmit={search} className="mt-10 max-w-4xl rounded-sm border border-white/20 bg-white/10 p-2 backdrop-blur-md"><div className="flex flex-col gap-2 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cidade, região ou tipo de imóvel..." className="w-full rounded-sm border-0 bg-white px-10 py-3 text-sm text-slate-900 outline-none"/></div><button className="rounded-sm bg-gold px-7 py-3 font-medium text-white hover:bg-gold-600"><Search className="mr-2 inline h-4 w-4"/>Pesquisar imóveis</button></div></form>
   </div></section>
  <section className="relative z-10 -mt-10 container-mw container-px"><div className="grid grid-cols-2 gap-4 md:grid-cols-4">{[[Building,'Imóveis','500+'],[Users,'Utilizadores','10k+'],[TrendingUp,'Vendas/mês','50+'],[Shield,'Verificados','100%']].map(([I,l,v])=>{const Icon=I as typeof Building; return <div key={String(l)} className="rounded-sm border border-border bg-card p-5 text-center shadow-sm"><Icon className="mx-auto mb-2 h-8 w-8 text-gold"/><div className="text-2xl font-bold">{String(v)}</div><div className="text-sm text-muted-foreground">{String(l)}</div></div>})}</div></section>
  <section className="container-mw container-px py-20"><div className="mb-8 flex items-end justify-between"><div><div className="gold-line mb-4"/><h2 className="font-serif text-3xl font-semibold">Imóveis em destaque</h2><p className="mt-1 text-muted-foreground">Oportunidades apresentadas com o padrão Kubata Kié.</p></div><Link to="/properties" className="hidden items-center gap-1 text-sm font-medium text-gold-700 sm:flex">Ver todos <ArrowRight className="h-4 w-4"/></Link></div>{loading?<div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{Array.from({length:6}).map((_,i)=><div key={i} className="skeleton-shimmer h-96 rounded-sm"/>)}</div>:<div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{featured.map((p,i)=><PropertyCard key={p.id} property={p} imageUrl={images[p.id]} priority={i<3}/>)}</div>}</section>
  <section className="bg-ink-900 py-20 text-white"><div className="container-mw container-px"><div className="mb-10"><div className="gold-line mb-4"/><h2 className="font-serif text-3xl font-semibold">Explore por categoria</h2></div><div className="grid grid-cols-2 gap-px overflow-hidden rounded-sm bg-white/10 md:grid-cols-3">{cats.map(([I,label,type])=><Link key={type} to={`/properties?property_type=${type}`} className="group bg-ink-900 p-7 transition hover:bg-ink-800"><I className="mb-5 h-7 w-7 text-gold"/><div className="font-serif text-lg">{label}</div><div className="mt-1 text-xs text-white/50">Explorar oportunidades</div><ArrowRight className="mt-5 h-4 w-4 text-white/40 transition group-hover:translate-x-1 group-hover:text-gold"/></Link>)}</div></div></section>
  <section className="container-mw container-px py-20"><div className="mb-10"><div className="gold-line mb-4"/><h2 className="font-serif text-3xl font-semibold">Onde procurar</h2></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{AREA_IMAGES.map(([name,province,img])=><Link key={name} to={`/properties?city=${encodeURIComponent(name)}`} className="group relative aspect-[4/5] overflow-hidden rounded-sm"><img src={img} alt={name} className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-ink-900/80 to-transparent"/><div className="absolute bottom-5 left-5 text-white"><div className="font-serif text-xl">{name}</div><div className="text-xs text-white/70">{province}, Angola</div></div></Link>)}</div></section>
  <section className="border-y border-border bg-white py-20"><div className="container-mw container-px"><div className="mx-auto max-w-3xl text-center"><div className="gold-line mx-auto mb-5"/><h2 className="font-serif text-3xl font-semibold">Da descoberta à decisão</h2><p className="mt-3 text-muted-foreground">Uma experiência imobiliária pensada para reduzir fricção e aumentar confiança.</p></div><div className="mt-12 grid gap-8 md:grid-cols-4">{[[Search,'Descobrir','Pesquise com filtros claros e relevantes.'],[Camera,'Explorar','Veja imagens, detalhes e localização.'],[Users,'Contactar','Fale com proprietários e agentes.'],[Shield,'Concluir','Acompanhe o processo com segurança.']].map(([I,t,d],i)=>{const Icon=I as typeof Search; return <div key={String(t)}><div className="mb-4 flex items-center gap-3"><span className="font-serif text-sm text-gold">0{i+1}</span><Icon className="h-5 w-5 text-gold"/></div><h3 className="font-serif text-lg">{String(t)}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{String(d)}</p></div>})}</div></div></section>
  <section className="bg-gold-50 py-16"><div className="container-mw container-px text-center"><h2 className="font-serif text-3xl font-semibold">Tem um imóvel para anunciar?</h2><p className="mx-auto mt-3 max-w-xl text-muted-foreground">Publique, acompanhe contactos e alcance compradores e inquilinos em toda Angola.</p><Link to="/properties/new" className="mt-7 inline-flex items-center gap-2 rounded-sm bg-ink-900 px-6 py-3 text-sm font-medium text-white hover:bg-ink-800">Publicar imóvel <ArrowRight className="h-4 w-4"/></Link></div></section>
 </div>
}
